#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
APP_ROOT="$OPENSHIFT_REPO_DIR/wsgi/afcon"
export PYTHONPATH="$PYTHONPATH:$APP_ROOT"
alembic -c "$APP_ROOT/alembic.ini" upgrade head