"""Added user model

Revision ID: 126495ce660
Revises: None
Create Date: 2014-03-03 22:33:11.447062

"""

# revision identifiers, used by Alembic.
revision = '126495ce660'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('pw_hash', sa.LargeBinary(), nullable=True),
    sa.Column('nick_name', sa.String(length=100), nullable=True),
    sa.Column('real_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
