"""empty message

Revision ID: 1edbabc929d
Revises: None
Create Date: 2014-03-04 18:14:55.193825

"""

# revision identifiers, used by Alembic.
revision = '1edbabc929d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('pw_hash', sa.LargeBinary(), nullable=True),
    sa.Column('nick_name', sa.String(length=100), nullable=True),
    sa.Column('real_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
