"""empty message

Revision ID: 2ef67e8aa5c
Revises: 1edbabc929d
Create Date: 2014-03-24 21:12:40.865274

"""

# revision identifiers, used by Alembic.
revision = '2ef67e8aa5c'
down_revision = '1edbabc929d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.LargeBinary(length=254), nullable=True))
    op.drop_column('user', 'pw_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pw_hash', sa.LargeBinary(), nullable=True))
    op.drop_column('user', 'password')
    ### end Alembic commands ###
